import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/m460/Source/startup_m460.c
Nuvoton/m460/Source/system_m460.c
""")

path = [cwd + '/Nuvoton/m460/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
