import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M2354/Source/system_M2354.c
Nuvoton/M2354/Source/startup_M2354.c
""")

path = [cwd + '/Nuvoton/M2354/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
