import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M480/Source/startup_M480.c
Nuvoton/M480/Source/system_M480.c
""")

path = [cwd + '/Nuvoton/M480/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
